title: JiuTian Simulations Documentation

description: Welcome!

remote_theme: rundocs/jekyll-rtd-theme

readme_index:
  with_frontmatter: true

author: [CSST Simulation Collaboration]

copyright:
  since: 2023 # like: 2000
  revision: false # is show the revision

gems:
  - jemoji

encoding: UTF-8

exclude:
  - Makefile
  - CNAME
  - Gemfile
  - Gemfile.lock